import { Box, ElevatedButton, OutlinedButton, Stack, Text } from "@md3-ui/core"
import { ChangeHistory } from "@md3-ui/icons"
import { NextPage } from "next"
import Head from "next/head"
import { MDXComponents } from "../src/mdx-components"

const Home: NextPage = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Box>
      <Box sx={{ maxWidth: 1488, mx: "auto", p: 18 }}>
        <svg
          width="40"
          height="40"
          viewBox="0 0 40 40"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M39.5 20c0 10.77-8.73 19.5-19.5 19.5S.5 30.77.5 20 9.23.5 20 .5 39.5 9.23 39.5 20Z"
            stroke="#000"
          />
          <path d="M6.5 6.5h27v27h-27v-27Z" stroke="#000" />
          <mask id="a" fill="#000">
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M33.928 6.07 20 33.928 6.07 6.07"
            />
          </mask>
          <path
            d="m20 33.928-.895.447.895 1.788.894-1.788-.894-.447ZM33.034 5.623 19.105 33.48l1.79.895L34.822 6.518l-1.789-.895ZM20.894 33.48 6.966 5.623l-1.79.895 13.93 27.857 1.788-.895Z"
            fill="#000"
            mask="url(#a)"
          />
        </svg>
        <Text variant="displayLarge">Material 3 UI</Text>
        <Text variant="headlineSmall">
          Get started with the Material 3 Design System for React Native.
        </Text>
        <Stack direction="row" spacing={4}>
          <ElevatedButton
            href="/docs/components/button"
            icon={<ChangeHistory />}
          >
            Documentation
          </ElevatedButton>
          <OutlinedButton>$ npm i @md3-ui/core</OutlinedButton>
        </Stack>
        <MDXComponents.ul>
          <MDXComponents.li>
            <Text sx={{ fontWeight: "500" }}>Accessible HTML</Text>. Support
            different devices and input modes, render semantic tags.
          </MDXComponents.li>
          <MDXComponents.li>
            <Text sx={{ fontWeight: "500" }}>High-quality interactions</Text>.
            Support gestures and multiple input modes (touch, mouse, keyboard).
          </MDXComponents.li>
          <MDXComponents.li>
            <Text sx={{ fontWeight: "500" }}>Reliable styles</Text>. Rely on
            scoped styles and automatic vendor-prefixing. Support RTL layouts.
          </MDXComponents.li>
          <MDXComponents.li>
            <Text sx={{ fontWeight: "500" }}>Responsive containers</Text>.
            Respond to element resize events.
          </MDXComponents.li>
          <MDXComponents.li>
            <Text sx={{ fontWeight: "500" }}>Incremental adoption</Text>.
            Interoperates with existing React DOM components. Bundle only what
            you use.
          </MDXComponents.li>
        </MDXComponents.ul>
      </Box>
    </Box>
  </>
)

export default Home
